# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kycomics' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Kycomics
    pod 'AFNetworking', '~> 3.0'
    pod 'TFHpple'
    pod 'MJExtension'
    pod 'SDWebImage', '~> 4.0'
    pod 'XXNibBridge', '~> 2.2'
    pod 'Masonry'

end
